server:
  port: 3344
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuelijun-dev/microservicecloud-config.git
          username: xuelijun_dev@163.com
          password: 965325li
          timeout: 1000000
